Repository AY2425S1-CS2103T-T14-4/tp, pull requests merged in 2024-11, with the labels that each got.

#178 Add panel and graph
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusPieChart.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusPieChart.fxml
  src/main/resources/view/css/DarkTheme.css
  src/main/resources/view/css/StatusPieChart.css
Labels: priority.High, alpha-bug

#194 Update ug to add known issue
  docs/UserGuide.md
  src/main/java/seedu/address/model/client/Remark.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: alpha-bug

#200 Finalize View Command Functionality on UI elements
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CloseCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/ClientDetailPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ClientDetailPanel.fxml
  src/main/resources/view/css/ClientDetailPanel.css
  src/main/resources/view/css/ClientListCard.css
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, alpha-bug

#206 Standardize pie chart legend labels
  src/main/java/seedu/address/ui/StatusPieChart.java
Labels: priority.High, alpha-bug

#307 Add improvement of error message as planned feature
  docs/DeveloperGuide.md
  docs/images/differentEditError.png
  docs/images/editErrorWithHint.png
  docs/images/incorrectPhoneEditError.png
Labels: [DG Issue]

#312 Update Filter Usage Guide and behaviour of Filter by Phone/Email in UG
  docs/UserGuide.md
Labels: [UG Issue]
